version: "2"

services:
  nginx:
    image: chainify/waves-nginx
    container_name: waves-nginx
    ports:
      - 80:80
      # - 6868:6868
      # - 6869:6869
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fullnode
    restart: always

  fullnode:
    image: chainify/waves-fullnode
    container_name: waves-fullnode
    volumes:
      - /root/.waves/mainnet:/root/.local/share/waves-mainnet
      - ./fullnode/configs:/root/.waves/configs
    command: bash -c "java -jar node/target/waves-all*.jar ../configs/waves-mainnet.conf"
    ports:
      - 6868:6868
      - 6869:6869
    tty: true
    stdin_open: true
    labels:
      - "autoheal=true"
    restart: always

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: waves-autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
