version: "2"

services:
  nginx:
    image: nginx
    container_name: waves-nginx
    ports:
      - 6868:6868
      - 6869:6869
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fullnode
    restart: always

  fullnode:
    image: wavesplatform/node
    container_name: waves-fullnode
    volumes:
      - /root/.waves/mainnet:/waves
    environment:
      - WAVES_NETWORK=MAINNET
      - WAVES_VERSION=latest
      - BRANCH=version-0.17.x
      - SBT_VERSION=1.2.8
      - WAVES_LOG_LEVEL=DEBUG
      - WAVES_HEAP_SIZE=2g
      - WAVES__REST_API__ENABLE=yes
      - WAVES__REST_API__BIND_ADDRESS=0.0.0.0
      - WAVES__REST_API__PORT=6869
      # - WAVES_WALLET_SEED=
      # - WAVES_WALLET_SEED_BASE58=
      # - WAVES_WALLET_PASSWORD=
      # - WAVES__REST_API__API_KEY_HASH=
    tty: true
    stdin_open: true
    labels:
      - "autoheal=true"
    restart: always

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: waves-autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
